### PR TITLE
Correct a typo in README

### PR DESCRIPTION
**Pull request by liu-jc**

### CODE REVIEW

**Comment by Tiiiger** [comment]
Merged! Thank you.

**Comment by liu-jc** [comment]
Hi Tianyi,

I have noticed that current version of this repo is different from former version few days ago. Because some functions in normalization.py I saw disappear now.  Seems like a rollback? Could you share what it is the difference between these two versions? Do you plan to recover/complete the full version?😂

Thx and looking forward to your reply.

Best regards,
Juncheng

**Comment by Tiiiger** [comment]
Hi Juncheng, 

I apologize for the confusion. I simply removed other normalizations because they are not used. The expected behavior of the sample script does not have any difference (if you want to replicate the paper reported result). 

Those normalization functions were there because I was doing some ablations. My preliminary result showed that AugNormAdj works consistently better so I didn't use any other normalization function.

**Comment by liu-jc** [comment]
Hi Tianyi,

Thanks for the reply! I not only want to replicate the main results but also want to exploring the ablations setting/results for academic research purpose. If you don’t mind, could you send me a former version? My email is juncheng.liu@u.nus.edu. This is a really impressive and interesting work. If we have any further work/outcome based on this, we will definitely cite your paper. Thanks a lot.

Best regards,
Juncheng

**Comment by Tiiiger** [comment]
Hi Juncheng,

Thanks for letting me know. Given that this may be a common request, I will clean the codes and push to a separate branch later today. You will see a couple more ablation choices regarding how to engineer better features with the propagation. 

We will include these additional results in the supplementary materials of our next version of the paper.

**Comment by liu-jc** [comment]
Really appreciate! Looking forward to your next version of the paper!

Best regards,
Juncheng

**Comment by Tiiiger** [comment]
See https://github.com/Tiiiger/SGC/tree/ablation

This branch is not entirely cleaned up. Feel free to open an issue if you have questions or if the code doesn't work.

**Comment by liu-jc** [comment]
Got it. Thank you so much!

**Pull request merged**
